### ISSUE TITLE
Tighten up libblockdev plugin requirements.

### ISSUE THREAD

**Issue by dwlehman** [storaged-project/blivet#891] opened 2020-08-19 17:53 UTC
Currently, the blivet spec file does not a `Requires` for any libblockdev plugin, but there are several (swap, crypto, loop, mdraid, mpath, dm) whose absence is not handled gracefully. We should either add them as hard requirements or add code to allow running without them.

**Comment by vojtechtrefny** [comment] 2022-01-24 15:54
Duplicate of #159

**Closed by vojtechtrefny** 2022-01-24 15:54 UTC
