### ISSUE TITLE
`_hidden` in class DeviceTreeBase does not match lvm filter 

### ISSUE THREAD

**Issue by bitcoffeeiux** [storaged-project/blivet#965] opened 2021-06-15 14:10 UTC
The devicetree under the current blivet uses the non-singleton mode when operating lvm filter, and blivet provides the copy function. therefore, if multiple blivet objects exist, `_hidden` in each object instance does not match lvm filter, resulting in an lvm disk operation exception

bugzilla:#1923910

**Comment by vojtechtrefny** [comment] 2021-06-17 14:15
Hi, the bug should be actually fixed by #959. You are right, the lvm filter not being changed during `Blivet.copy()` is a problem, but we have mechanisms to deal with that and remove devices that will be used from it. But because the filter is currently a list we end up adding the device to it multiple times and removing it only once, that's what #959 fixes.

**Comment by bitcoffeeiux** [comment] 2021-06-17 14:36
This is indeed an improvement, but in fact #1923910 is much more complicated than this, because Anaconda has an exception in the process logic that causes the unhide() function to not be called in multiple instances to remove the selected disk from the filter

**Comment by vojtechtrefny** [comment] 2021-06-18 11:08
I tried to reproduce the issue using the steps you provided in the bugreport and #959 fixes it for me. You can try [this updates image](https://vtrefny.fedorapeople.org/img/rhbz1923910.img) for Fedora 34. Maybe I'm missing some steps, but I was able to reproduce the bug with unpatched F34. Even the storage.log from the bugreport suggests this is the same problem: we are are removing the *fedora* VG from the LVM filter before trying to work with it, but the problem is it was added three times and removed only twice:

```
$ grep "lvm filter: adding fedora to the reject list" storage.log | wc -l
3

$ grep "lvm filter: removing fedora from the reject list" storage.log | wc -l
2
```

**Comment by bitcoffeeiux** [comment] 2021-06-18 12:04
great, I have tried to test it and it is fine, but I am still confused in some places. Maybe I need to think about it more carefully.

**Closed** 2021-11-23 13:29 UTC
